apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pzm2vakbr-java-springboot
  janus-idp.io/tekton: pzm2vakbr-java-springboot
  backstage.io/kubernetes-id: pzm2vakbr-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pzm2vakbr-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
